name: niitgeofence
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.5
  cloud_firestore:
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.21+15
  location: ^3.0.2
  geo_firestore: ^0.0.1
  video_player: ^0.10.11+2
  audioplayers: ^0.15.1


  ##  geofence:
#  cloud_firestore: ^0.13.6
#  geolocator: ^5.3.2+2
#  google_maps_flutter: ^0.5.21+15
#  location: ^3.0.2

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Safar.png"

flutter:

  uses-material-design: true

  assets:
    - assets/car_icon.png
    - assets/1.png
    - assets/splash.mp4
    - assets/q1.jpg
    - assets/t1.jpg
    - assets/k1.jpg
    - assets/qq1.jpg
    - assets/a1.jpg
    - assets/Safar.png
    - assets/Q3.jpg
    - assets/d.mp3
    - assets/e.mp3
